config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :cars, only: [:new, :create]
  end
  resources :cars, only: [:index, :show] do
    resources :reservations, only: [:create, :edit]
  end
  resources :reservations, only: [:index, :show]
  patch "reject/reservations/:id", to: "reservations#reject", as: "reject"
  patch "confirm/reservations/:id", to: "reservations#confirm", as: "confirm"
  patch "cancel/reservations/:id", to: "reservations#cancel", as: "cancel"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :reservations
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  validates :price, presence: true
  validates :model, presence: true
  validates :brand, presence: true
  validates :address, presence: true
  validates :description, presence: true
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_address, against: :address,
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :car
  belongs_to :user
  validates :status, inclusion: { in: ["pending", "confirmed", "rejected", "cancelled"] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cars
  has_many :reservations
  validates :email, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :authenticate_user!, only: [:home, :index, :show]

  private

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

   def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_user, only: [:new, :create]

  def new
    @car = Car.new
  end

  def create
    # hello
    @car = Car.new(car_params)
    @car.user = @user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def update
  end

  def index
    if params[:query].present?
      @cars = Car.geocoded #returns cars with coordinates

      @cars = Car.where("address ILIKE ?", "%#{params[:query]}%")

      @markers = @cars.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude
      }
      end
    else
      @cars = Car.geocoded #returns cars with coordinates
      @cars = Car.all

      @markers = @cars.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude
      }
      end
    end
  end

  def show
    @car = Car.find(params[:id])
    @reservation = Reservation.new
    @markers = [{
      lat: @car.latitude,
      lng: @car.longitude
    }]
  end

  def destroy
  end

  def edit
  end

  private

  def car_params
    params.require(:car).permit(:price, :model, :brand, :address, :description, :photo)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_car, only: [:new, :create]


  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.car = @car
    if @reservation.save
      redirect_to reservation_path(@reservation)
    else
      # hello
      render "cars/show"
    end
  end

  def index
    @reservations = Reservation.all
    @user_reservations = Reservation.where(user_id: current_user.id)
    @user_cars = Car.where(user_id: current_user.id)
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def reject
    @reservation = Reservation.find(params[:id])
    @reservation.status = "rejected"
    @reservation.save
    redirect_to reservations_path
  end

  def cancel
    @reservation = Reservation.find(params[:id])
    @reservation.status = "cancelled"
    @reservation.save
    redirect_to reservations_path
  end

  def confirm
    @reservation = Reservation.find(params[:id])
    @reservation.status = "confirmed"
    @reservation.save
    redirect_to reservations_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end

  def set_car
    @car = Car.find(params[:car_id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  protected
 # devise redirect
  def after_sign_up_path_for(resource)
    stored_location_for(resource) || super
  end
end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/create.html.erb
<h1>Car#create</h1>
<p>Find me in app/views/car/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Car#destroy</h1>
<p>Find me in app/views/car/destroy.html.erb</p>

app/views/cars/edit.html.erb
<h1>Car#edit</h1>
<p>Find me in app/views/car/edit.html.erb</p>

app/views/cars/index.html.erb
<div class="container">

  <% if @cars.count > 1 %>
    <h1 id="h1-results"><%= @cars.count %> cars found</h1>
  <% elsif @cars.count == 1 %>
    <h1 id="h1-results"><%= Car.search_by_address(params[:query]).count %> car found</h1>
  <% elsif Car.search_by_address(params[:query]).count == 0 %>
    <h1 id="h1-results"> No cars found, please try another location.</h1>
  <% end %>
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="row">
          <% @cars.each do |car| %>
            <div class="col-12 col-md-6 m-0 p-0">
              <%= link_to car_path(car) do %>
                <div class="car-card m-2 p-2">
                  <%= cl_image_tag car.photo, class: "card-photo" %>
                  <div class="card-info">
                    <p><%= car.brand %>  <%= car.model %></p>
                    <p>€ <%= car.price %> / day</p>
                  </div>
                </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-4 mt-3 ">
      <div
        id="map"
        style="width: 100%; height: 500px; border-radius: 4px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container" style="min-height: 75vh;">
  <div class="row justify-content-center">
    <div class="col-xs-12 col md-4">
      <h2 class="text-center">Upload your car</h2>
      <%= simple_form_for([@user, @car]) do |c| %>
        <div class="form-inputs col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
          <%= c.input :brand %>
          <%= c.input :model %>
          <%= c.input :price %>
          <%= c.input :address %>
          <%= c.input :description %>
          <%= c.input :photo %>
          <%= c.input :photo_cache, as: :hidden %>
          <div class="form-actions">
          <%= c.button :submit, "Submit", class: "main-cta-login1" %>
        </div>
          <% end %>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="card-trip col-8 border pt-1">
      <div class="d-flex justify-content-between" >
        <div class="mt-3">
          <h2><%= @car.brand %> - <%= @car.model %></h2>
          <p><%= @car.address %></p>
          <p><%= @car.description %></p>
        </div>
      </div>
      <%= cl_image_tag @car.photo %>
    </div>
  <div class="pl-3 col-4">
    <div class="border p-2">
      <div class="d-flex justify-content-between p-2">
        <p id="price">Book this <%= @car.brand %> for <%= @car.price %>€/day</p>
      </div>
  <!-- test -->
      <div class="d-flex justify-content-between p-2">
        <%= simple_form_for([@car, @reservation])  do |c| %>
        <div class="form-inputs pt-0">
          <%= c.input :start_date %>
          <%= c.input :end_date %>
        </div>
        <div class="form-actions">
         <%= c.button :submit, "Book now", class: "main-cta mb-3"  %>
       </div>
       <% end %>
      </div>
      <div>
        <p class="pt-3" style="font-size:20px;">Car location</p>
      </div>
      <div
        id="map"
        style="width: 100%;
        height: 300px;
        border-radius: 4px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>
<br>
<p class="text-left" style="font-size:18px;"><%= link_to "Back to all cars", cars_path %></p>
</div>


<% # update %>

app/views/cars/test_front.html.erb
<!--   <h1 class="h1-results"><%#= Car.count %> cars in Barcelona</h1> -->
  <!-- a -->


<!-- <div class="web-container"> -->
  <h1 class="h1-results"><%= Car.count %> cars in Barcelona</h1>
  <div class="container">
    <div class="row justify-content-center">
      <div class="cars-list">
       <% @cars.each do |car|  %>
       <div class="col-xs-12 div col-md-4">
          <div class="car-card">
            <%= link_to car_path(car) do %>
            <%= cl_image_tag car.photo, class: "card-photo"  %>
              <div class="car-price">
                <p><%= car.brand %>  <%= car.model %></p>
                <p>€ <%= car.price %> / day</p>
              </div>
            <% end %>
          </div>
      <!-- </div> -->
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/update.html.erb
<h1>Car#update</h1>
<p>Find me in app/views/car/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
       <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>

       <!-- Bootstrap responsiveness -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body style="font-family:'Roboto', sans-serif">

    <%= render "shared/navbar" %>



    <%= yield %>


    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
</div>

<div class="web-container">
  <h1>Rent the perfect car</h1>
  <p>Search in seconds among thousands of cars</p>
  <div id="search-container"><%= form_tag cars_path, class: "search", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Enter location"%>
  </div>
  <%= submit_tag "Search", class: "home-cta" %>
   <%end%>
</div>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Here you can see the status of your reservation</h1>

<% # renter %>
<% # if reservation_user_id = current_user_id => (renter), then change status: %>
<% #from pending to cancel & confirmed to cancel %>
<% if @reservation.user_id == current_user.id %>
<div>
  <%= @reservation.status%>
<button type="button" class="btn btn-danger">cancel</button>
<i class="fas fa-sync"></i>
<% # car owner %>
<% # if reservation_user_id != current_user_id => (onwer), then change status: %>
<% #from pending to confirmed & from pending to rejected & from confirmed to cancel %>
<% elsif @reservation.status == "pending" %>
<h2 style="color: orange"><%= @reservation.status %></h2>
<%= link_to "approve", approve_path, {method: :patch}%>
<%= link_to "reject", reject_path, {method: :patch}%>
<% else %>
<button type="button" class="btn btn-danger">cancel</button>
<% end %>

app/views/reservations/index.html.erb
<div class="container" style="min-height: 75vh;">
  <div class="row">
    <div class="col-12 col-md-6">
      <h2>Your reservations</h2>
      <%= link_to "Refresh", reservations_path%>
      <% @user_reservations .each do |reservation| %>
      <div class="car-reservation-card">
        <img src= <%= "#{Car.find(reservation.car_id).photo}" %>>
        <div class="car-reservation-info">
          <h2> <%= "#{Car.find(reservation.car_id).model} / #{Car.find(reservation.car_id).brand}" %></h2>
          <p><%="#{reservation.start_date} - #{reservation.end_date}"%></p>
          <p><%="#{reservation.status}"%></p>
          <p>
            <% if reservation.status != "cancelled"%>
            <%= link_to "cancel", cancel_path(reservation.id), {method: :patch}%>
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
    </div>
  <div class="col-12 col-md-6">
    <h2 id="car-rentals">Your car rentals</h2>
    <% @user_cars.each do |car| %>
      <% @reservations.each do |booking| %>
        <% if booking.car_id == car.id %>
          <div class="car-reservation-card">
            <img src= <%= "#{car.photo}" %>>
            <div class="car-reservation-info">
              <h2><%="#{car.brand} - #{car.model}" %></h2>
              <p><%="#{User.find(booking.user_id).email}" %></p>
              <p><%="#{booking.start_date} - #{booking.end_date}" %></p>
              <p><%="#{booking.status}" %></p>
                <% if booking.status == "pending" %>
                    <div class="d-flex justify-content-between" >
                   <%= link_to "confirm", confirm_path(booking.id), {method: :patch}%>
                     <%= link_to "reject", reject_path(booking.id), {method: :patch}%>
                    </div>
                <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<% days = (@reservation.start_date..@reservation.end_date).count %>
  <% cost = days * @reservation.car.price %>




<div class="card col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4 " style="width: auto; border-color: #80D6BD; border-radius: 10px;">
  <h5 class="card-title text-center" style="font-size: 2em; padding-top: 19px;">Thank you, <%=current_user.first_name%>!</h5>
 <%= cl_image_tag @reservation.car.photo, class: "car" %>
  <div class="card-body">

    <p1 class="card-text text-center" style="font-size: 18px;"><strong>Your reservation is now pending the car's owner review</strong></p1>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>Start date:</strong> <%= @reservation.start_date%></li>
    <li class="list-group-item"><strong>End date: </strong> <%= @reservation.end_date%></li>
     <li class="list-group-item"><strong>Total price: </strong> <%= cost %>€</li>
    <li class="list-group-item"><strong>Confirmation number: </strong> <%= @reservation.id%></li>
  </ul>
  <div class="card-body">
    <p href="#"> You may review your pending requests in your <%= link_to "dashboard", reservations_path %>.</p>
    <a href="#" class="card-link"><%= link_to "Back to all cars", cars_path %></a>
  </div>
</div>
<% # update %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Supercharged by <i class="fas fa-rocket"></i> Boost-it!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar shadow-sm navbar-expand-sm navbar-light navbar-lewagon">
  <div class = "d-flex justify-content-left">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

    <% if controller_name === "pages" %>
      <h2 class="logo-type"> CarsBnB </h2>
  </div>
  <div>
    <% else %>
      <%= form_tag cars_path, class: "search", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "🔍 Enter location"%>
      <% end %>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%if user_signed_in? == true %>
            <li id="welcome-message">Welcome <%= current_user.first_name %> </li>
            <li><%= link_to "Rent your car", new_user_car_path(current_user), class: "nav-button" %> </li>
           <% else %>
           <li> <%= link_to "Sign up", new_user_registration_path(@user_id), class: "nav-link" %> </li>
           <li> <%= link_to "Log in", new_user_session_path(@user_id), class: "nav-link" %> </li>
           <li> <%= link_to "Rent your car", new_user_session_path(@user_id), class: "nav-button" %> </li>
           <%end%>
      </li>
      <%if user_signed_in? == true %>
        <li class="nav-item dropdown">
          <%= image_tag "burger_menu.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", reservations_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      <% else %>
          <%=  %>
       <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/create.html.erb</p>